"""Small file IO helpers used by the reconstruction pipeline."""

from __future__ import annotations

import ast
import json
from pathlib import Path
from typing import Any

import numpy as np

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}


def ensure_dir(path: str | Path) -> Path:
    target = Path(path)
    target.mkdir(parents=True, exist_ok=True)
    return target


def list_images(path: str | Path) -> list[Path]:
    source = Path(path)
    if source.is_file():
        return [source]
    if not source.exists():
        raise FileNotFoundError(f"Image path does not exist: {source}")
    return sorted(p for p in source.iterdir() if p.suffix.lower() in IMAGE_EXTENSIONS)


def write_json(path: str | Path, payload: dict[str, Any]) -> Path:
    target = Path(path)
    ensure_dir(target.parent)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return target


def _format_scalar(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (int, float)):
        return repr(float(value)) if isinstance(value, float) else repr(value)
    if isinstance(value, np.ndarray):
        return json.dumps(value.tolist())
    if isinstance(value, (list, tuple)):
        return json.dumps(value)
    if value is None:
        return "null"
    return json.dumps(value)


def write_simple_yaml(path: str | Path, payload: dict[str, Any], header: str | None = None) -> Path:
    """Write a simple YAML subset without adding a PyYAML dependency."""
    target = Path(path)
    ensure_dir(target.parent)
    lines: list[str] = []
    if header:
        lines.append(f"# {header}")
    for key, value in payload.items():
        lines.append(f"{key}: {_format_scalar(value)}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def read_simple_yaml(path: str | Path) -> dict[str, Any]:
    """Read the simple one-key-per-line YAML subset written by this project."""
    payload: dict[str, Any] = {}
    for raw_line in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        value = raw_value.strip()
        if value == "null":
            payload[key.strip()] = None
            continue
        try:
            payload[key.strip()] = ast.literal_eval(value)
        except (SyntaxError, ValueError):
            payload[key.strip()] = value.strip('"')
    return payload


def save_intrinsics_yaml(
    path: str | Path,
    camera_matrix: np.ndarray,
    distortion_coefficients: np.ndarray,
    image_size: tuple[int, int],
    reprojection_error_px: float | None = None,
    per_image_errors_px: list[float] | None = None,
    metadata: dict[str, Any] | None = None,
) -> Path:
    payload: dict[str, Any] = {
        "model": "pinhole_radtan",
        "image_width": int(image_size[0]),
        "image_height": int(image_size[1]),
        "camera_matrix": np.asarray(camera_matrix, dtype=float).tolist(),
        "distortion_coefficients": np.asarray(distortion_coefficients, dtype=float).reshape(-1).tolist(),
        "reprojection_error_px": None
        if reprojection_error_px is None
        else float(reprojection_error_px),
    }
    if per_image_errors_px is not None:
        payload["per_image_errors_px"] = [float(v) for v in per_image_errors_px]
    if metadata:
        for key, value in metadata.items():
            payload[f"metadata_{key}"] = value
    return write_simple_yaml(path, payload, header="Generated by reconbot calibration.")


def load_intrinsics_yaml(path: str | Path) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    payload = read_simple_yaml(path)
    camera_matrix = np.asarray(payload["camera_matrix"], dtype=float)
    distortion = np.asarray(payload.get("distortion_coefficients", []), dtype=float).reshape(-1, 1)
    return camera_matrix, distortion, payload


def save_point_cloud_ply(
    path: str | Path,
    points: np.ndarray,
    colors: np.ndarray | None = None,
) -> Path:
    target = Path(path)
    ensure_dir(target.parent)
    pts = np.asarray(points, dtype=float).reshape(-1, 3)
    cols = None if colors is None else np.asarray(colors).reshape(-1, 3)
    if cols is not None and len(cols) != len(pts):
        raise ValueError("colors must have the same number of rows as points")
    has_color = cols is not None

    header = [
        "ply",
        "format ascii 1.0",
        f"element vertex {len(pts)}",
        "property float x",
        "property float y",
        "property float z",
    ]
    if has_color:
        header.extend(["property uchar red", "property uchar green", "property uchar blue"])
    header.append("end_header")

    with target.open("w", encoding="utf-8") as handle:
        handle.write("\n".join(header) + "\n")
        if has_color:
            color_u8 = np.clip(cols, 0, 255).astype(np.uint8)
            for point, color in zip(pts, color_u8, strict=True):
                handle.write(
                    f"{point[0]:.8f} {point[1]:.8f} {point[2]:.8f} "
                    f"{int(color[0])} {int(color[1])} {int(color[2])}\n"
                )
        else:
            for point in pts:
                handle.write(f"{point[0]:.8f} {point[1]:.8f} {point[2]:.8f}\n")
    return target


def load_ascii_ply_points(path: str | Path) -> np.ndarray:
    source = Path(path)
    lines = source.read_text(encoding="utf-8").splitlines()
    try:
        end_header = lines.index("end_header")
    except ValueError as exc:
        raise ValueError(f"Not an ASCII PLY file written by this project: {source}") from exc
    points: list[list[float]] = []
    for line in lines[end_header + 1 :]:
        if not line.strip():
            continue
        fields = line.split()
        points.append([float(fields[0]), float(fields[1]), float(fields[2])])
    return np.asarray(points, dtype=float)
